# permissions for end users to view agents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: agent-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spacetraders-operator
    app.kubernetes.io/part-of: spacetraders-operator
    app.kubernetes.io/managed-by: kustomize
  name: agent-viewer-role
rules:
- apiGroups:
  - spacetraders.hafer.dev
  resources:
  - agents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spacetraders.hafer.dev
  resources:
  - agents/status
  verbs:
  - get
